Algoritmo para tradução de número para número por extenso.
malvinus/NumberToWordsAPI pull request #1
Opened 2019-07-03 15:58 UTC by malvinus

### Como funciona?

O algoritmo é baseado no princípio que, a cada 3 dígitos, as regras para a escrita por extensa dos números é a mesma, ou seja, a cada três números temos: unidade, dezena e centena. Assim, basta quebrar o número em grupos de 3 números e diferenciar as classes desses dígitos, no caso deste algoritmo são apenas duas: primeira e segunda classe.

2019-07-04 18:33 UTC, mzr-certi requested changes
Ficou bem difícil seguir o fluxo completo do código via PR, tem várias coisas que já estão no master (e não aparecem direito aqui) ou diffs de coisas mudando de lugar, etc.

Podes fazer um `git reset` no master (ou alterar o target do PR pra um branch vazio?) pfv? Acredito que isso seja suficiente pro código aparecer todo no PR pra ser revisado.

2019-07-04 18:33 UTC, mzr-certi commented on index.js
> +const uniqueTens = require("./enums").uniqueTens;
meio feio fazer dois requires, um destructuring ia ajudar na legibilidade

2019-07-08 16:33 UTC, mzr-certi commented
> ### Como funciona?
> O algoritmo é baseado no princípio que, a cada 3 dígitos, as regras para a escrita por extensa dos números é a mesma, ou seja, a cada três números temos: unidade, dezena e centena. Assim, basta quebrar o número em grupos de 3 números e diferenciar as classes desses dígitos, no caso deste algoritmo são apenas duas: primeira e segunda classe.

up

2019-07-08 18:33 UTC, malvinus commented
@mzr-certi desculpa a demora para responder. A notificação da primeira mensagem acabou se perdendo dentre as outras notificações do GitHub e acabei não vendo. Assim que chegar em casa e ter acesso a um PC faço o que você pediu e quando finalizar volto aqui para te avisar. Obrigado!

2019-07-09 02:52 UTC, closed without merging

2019-07-09 03:05 UTC, malvinus commented
@mzr-certi Criei um novo pull request: https://github.com/malvinus/NumberToWordsAPI/pull/2
Infelizmente o GitHub fechou este automaticamente quando tentei mudar o target dele. Acho que agora está certinho.